spring:
  application.name: orders-ws
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/mongodb}

eureka:
  client.serviceUrl.defaultZone: ${EUREKA_URL:http://localhost:7100/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}
    non-secure-port: ${PUBLIC_PORT:7003}
    secure-port: ${PUBLIC_PORT:7003}

server:
  port: ${PORT:7003}

feign:
  client:
    config:
      default:
        connectTimeout: 12000
        readTimeout: 12000
        loggerLevel: basic
